apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-deploy-blue
  namespace: route
  labels:
    route: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      route: blue
  template:
    metadata:
      namespace: route
      labels:
        route: blue
    spec:
      containers:
        - name: route
          image: {{ .Values.ACCOUNT_ID }}.dkr.ecr.{{ .Values.AWS_REGION }}.amazonaws.com/gateway:{{ .Values.BLUE_ROUTE_TAG }}
          volumeMounts:
          - name: route-blue
            mountPath: /etc/nginx/conf.d/
          ports:
          - name: web
            containerPort: 80
            protocol: TCP
      volumes:
      - name: route-blue
        configMap:
          name: route-blue
