apiVersion: v1
kind: Service
metadata:
  name: nginx-service-blue
  namespace: blue
spec:
  selector:
    app: nginx
    nginx/version: "IMAGE_TAG"
  ports:
    - name: web
      port: 80
  type: ClusterIP

