apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  namespace: blue
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: blue
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.ACCOUNT_ID }}.dkr.ecr.{{ .Values.AWS_REGION }}.amazonaws.com/ecr_images_from_jenkins:{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.LIMIT_CPU }}
          requests:
            cpu: {{ .Values.REQUEST_CPU }}
