apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  namespace: green
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: green
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.ACCOUNT_ID }}.dkr.ecr.{{ .Values.AWS_REGION }}.amazonaws.com/ecr_images_from_jenkins:{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
