apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-green
  namespace: green
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-green
  minReplicas: {{ .Values.MIN_COUNT }}
  maxReplicas: {{ .Values.MAX_COUNT }}
  targetCPUUtilizationPercentage: {{ .Values.CPU_PERCENT }}
